version: '3'

volumes:
  mysql:

services:
  db:
    image: mysql:8.0
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}:3306
